modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/QKDream/Create-Fire-Control---Fire-Control-Eye/issues"

[[mods]]
modId="firecontrolcompat"
version="1.1.0"
displayName="机械动力：先进火控：火控之眼 (Create: Fire Control - Fire Control Eye)"
description='''
让机械动力火炮·先进火控的显示连接器雷达/自动反导与火控计算机雷达识别并锁定 vestalihy、CBCMS（航空炸弹/鱼雷/火箭弹/深水炸弹）以及 TAOV（地狱火/Tau）等弹药；新增架束近炸导弹与红外锁定导弹（地面型/空射型），并补齐 TWS 多目标跟踪、光电锁定弹药、目标类型标注与提前量指示。
'''
authors="qkdream"

[[dependencies.firecontrolcompat]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.firecontrolcompat]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.firecontrolcompat]]
    modId="create_fire_control"
    type="required"
    versionRange="[0.1.0,1.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.firecontrolcompat]]
    modId="mianbaos_modernwarfare"
    type="required"
    versionRange="[2.4.5,)"
    ordering="AFTER"
    side="BOTH"

[[mixins]]
config="firecontrolcompat.mixins.json"
